### ISSUE TITLE
keybind.var-section not working

### ISSUE THREAD

**Issue by AndersAskeland** [rostools/r-cubed-intro#35]
In section 5.7, the key bind.var-section is not working. 

<img width="693" alt="image" src="https://github.com/rostools/r-cubed-intro/assets/16804386/b9a9ecdb-c478-40ca-b621-782cf9ab1b78">

Dont know why, as it is specified in _variables.yml.

Maybe a build time error that is automatically fixed on next build.

**Comment by lwjohnst86** [comment]
Fixed
